### ISSUE TITLE
Confirm we can build all leader content types (questions)

### ISSUE THREAD

**Issue by austinpapp** [PowerlineApp/powerline-server#210]
# Overview
Currently, there only seems we can build a subset of the expected leader questions base on reviewing the form validation: https://github.com/PowerlineApp/powerline-server/blob/develop/backend/src/Civix/ApiBundle/Form/Type/Poll/QuestionType.php

Current questions: 
* event (group_event)
* payment request / crowd fundraiser (group_payment_request)
* petition (group_petition)

Missing questions:
* poll
* discussion (group_news)

# Action / Work
1. If we are missing the above questions, let's build those out just like the rest of the questions
2. If we are not missing those questions, please document here where that information is.

**Comment by austinpapp** [comment]
@jterps08 can you explain where discussions where built? i dont see any real references to it. was it maybe called something else?

**Comment by jterps08** [comment]
To the best of my knowledge, discussions are simply 'questions' without 'answers'. Very little in the Mikhail wiki. https://github.com/PowerlineApp/powerline-server/wiki/Discussion. May be easier to inspect FrontendBundle on Bitbucket v1 code repo.

**Comment by austinpapp** [comment]
ok. so can you give me an idea as to what this solves and how we are to handle it? like i said, i really didnt see much about it in the code base.

**Comment by jterps08** [comment]
I'm not sure if I understand your question...

A leader can create a discussion. It's an item that is delivered to all group members with a push notification alert and is considered priority zone content. Discussions can be upvoted and downvoted, but they cannot be boosted because 1) everyone has already received a push notification, and 2) it's already in the priority zone. Discussions don't have any options. They're just for people to comment on. Users can see total count of upvotes/downvotes on a discussion.

Compare this to a normal user post where 1) only the user's followers get a notification, 2) users can upvote/downvote the post to try to get it boosted to all group members, 3) it is not priority zone unless it is boosted. Users cannot see the number of upvotes/downvotes for a post, only percentage.

In large group dynamics, there's two scenarios we're trying to solve for: A) A scenario in which the group leader (who is also a de facto group member) wants everyone to receive a notification for the discussion post he is making, and B) A scenario in which the group leader (who is also a de facto group member) does not want everyone to receive a notification (only his followers) when he makes his post. 

I am open to alternatives, whatever's easiest. I could see a future where we get rid of the Discussion concept and simply give the group-leader/manager the option to (notify all members? notify only followers) when making a post and effectively boosting the post as it is published. 

The issue of seeing total number of upvotes/downvotes can be solved/addressed as separate issue - the psychology of letting people see this number in a pre-boosting situation is that it could inadvertently influence if people upvote/downvote something because they know it's close to getting boosted. Thoughts @austinpapp

**Comment by austinpapp** [comment]
@igaponov we can build out most of what we need already. thats in the polls endpoint. however, we need to finish the work. the frontendbundle has logic that will properly publish the question, update appropriate tables for visibility and push to the message queue.

what questions do you have?

**Comment by jterps08** [comment]
This is very high priority.
