### ISSUE TITLE
ACL Security Enhancement for SSO Leader Experience

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#23]
Currently, a Powerline user has one login for the mobile app and a second, separate login to manage the group. We need this to be one unified experience for the user so that when a user logs into the web app, the system knows if s/he has group owner/manager/member rights or not and provides appropriate access controls accordingly. 

For example, in the future, once the user logs into the app and visits a group, the system will show the Content Creation (see attached) or Group Management functionality IF the user is a group owner/manager. If the user is not authorized, s/he will not be able to access these controls. 

Related: When a user creates a group in the future, the system associates the user as the group creator/owner.
Related: When a user logs into the web app in the future, the system does not require him to log in with a separate set of credentials to manage the group. The system will be able to show a "manage" button as seen in attached picture below to the authorized group creator/owner and managers.
Related: A group owner can assign any group member(s) to have group manager privileges, but the users must be group members first. 
Related: Issue #22 

![manage button for group](https://cloud.githubusercontent.com/assets/7582457/11853730/bc16ea9a-a40d-11e5-8fe6-288f4dc6f515.png)

**Comment by shakaran** [comment]
WIP in branch https://github.com/shakaran/powerline-server/tree/acl-improvements-issue-23

Implementing a regular website "user", I called "webuser", since the API user is called "mobileuser". So all security ACL for the webuser will be under "/user/", that is:

  /user/login
  /user/registration
  /user/facebook/login
  /user/registration-facebook
  /user/forgot-password
  /user/resettoken/
  /user/beta

Pending to replicate each entry point functionality and logic from API (mobileuser) to regular web (webuser)

**Comment by shakaran** [comment]
After merge PR #93 we have now support for login several types of users under /api/secure/login

Pending to implement unit test for ensure the behaviour after future changes

**Comment by shakaran** [comment]
@austinpapp @jterps08 this issue should be closed?
