### ISSUE TITLE
Create Copy/Paste-able Scripts for Leader Content Creation

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-server#255]
We need to provide Peter with the ability to easily create leader content in a group for the purpose of testing newsfeed content loading and sorting as well as push notifications. Please create a test 'script' that Peter can use to test leader content creation (e.g. with https://apigee.com/console/others)

We are testing all properties, so please include all information (see note below) when creating the following

- Poll
- Leader-Petition
- Discussion
- Fundraiser (without Goal and Deadline)
- Crowdfunder (Goal and Deadline)
- Event

Note: like attached picture, or youtube link - anything that the frontend uses.

**Comment by igaponov** [comment]
@jterps08 there is a Sandbox mode (just like apigee):
![image](https://cloud.githubusercontent.com/assets/4271889/17820277/77702bac-6665-11e6-8979-c30b7cff516b.png)
is it not enough?

**Comment by jterps08** [comment]
I did not know about this... @austinpapp @petervojtek is this sufficient?

**Comment by austinpapp** [comment]
as long as it creates content, i dont much care what does it... i assume it works as expected.

**Comment by jterps08** [comment]
Peter do you need instruction on how to use this?

**Comment by petervojtek** [comment]
@jterps08 , yes, I am aware of this sandbox UI (Igor showed me it for some other use case).
If the leader-content api endpoints work, then this is very good approach and I will use it (actually I trought that the leader-content related API endpoints and their corresponding backend business logic are broken to some extent -- at least that was my feeling from Austin's attempts to create the leader content).

**Comment by jterps08** [comment]
Thank you @petervojtek ... @austinpapp what do we need here. My understanding is that leader content works. Did we build the publish endpoint yet? If not, do we have an issue for it? That might be the problem here...

**Comment by jterps08** [comment]
So it seems we have the PATCH command that we can use according to Igor for publishing/testing leader content.
https://api-dev.powerli.ne/api-doc#patch--api-v2-polls-{id}

PATCH  /api/v2/polls/{id}

**Comment by austinpapp** [comment]
all leader content has the ability to be created and published. we just don't have a good way to build content right now. as time permits i've been working on some python to handle this but its no where near ready to just beat on. 

my suggestion here is maybe we leverage symfony commands to do it. @igaponov it should be pretty easy to generate some mock content this way. for the mean time you or i can execute the command. otherwise i'm not sure of the best way w/o our involvement every time.

**Comment by jterps08** [comment]
I understand that we don't have a frontend to create leader content, but we now have the POST and PATCH endpoints needed to do this via API. 
I'm okay with using Apigee or Sandbox to create and publish leader content for mobile testing purposes.
I am aware of the API documentation but I do not have the time to figure this out right now... I need an example to work with and we can take it from there and duplicate it for the other types of leader content. 

Please give me an example POST and PATCH for creating a test poll in some group with as many fields provided as would be possible from a frontend, and I will duplicate/modify/test with Peter.

**Comment by petervojtek** [comment]
@jterps08 , actually I created myself this small helper which is calling the leader API from mobile app. It is not attached to UI, so that one must call it from source code, but this is the way I am about to use the leader API:
https://github.com/PowerlineApp/powerline-mobile/blob/develop/www/js/services/leader-content-helpers.js

but I will play with this issue bit later..

**Comment by jterps08** [comment]
Thank you Peter
